name: lint

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17.0
      - name: Compile
        run: sbt scalafmtSbtCheck scalafmtCheckAll compile
